server:
  port: 8080

logging:
  level:
    com.microservice.prices: DEBUG
    root: INFO

# H2 Database
# Enabling the H2 console
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# Flyway Properties
flyway:
  enabled: true
  locations: classpath:/db/migration
  baseline-on-migrate: true
